{{- if .Values.sentinel.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-sentinel-headless
  namespace: {{ include "redis.namespace" . }}
  labels: {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: sentinel
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-sentinel
      port: {{ .Values.sentinel.service.ports.sentinel }}
      targetPort: tcp-sentinel
  selector: {{- include "redis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sentinel
{{- end }}
