apiVersion: v2
name: cassandra
description: Apache Cassandra distributed NoSQL database
type: application
version: "0.1.0"
appVersion: "5.0.6"
icon: https://cdn.simpleicons.org/apachecassandra
home: https://github.com/kubelauncher/charts
sources:
  - https://github.com/kubelauncher/docker
  - https://github.com/kubelauncher/charts
maintainers:
  - name: kubelauncher
    email: platform@kubelauncher.com
    url: https://www.kubelauncher.com
keywords:
  - cassandra
  - nosql
  - database
  - wide-column
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: "cosign"
  artifacthub.io/changes: |
    - kind: added
      description: Initial release of cassandra chart (appVersion 5.0.6)
