apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}-hl
  namespace: {{ include "mongodb.namespace" . }}
  labels: {{- include "mongodb.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
  {{- with .Values.primary.service.headless.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-mongodb
      port: {{ include "mongodb.servicePort" . }}
      targetPort: tcp-mongodb
  selector: {{- include "mongodb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: primary
