apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ include "mongodb.namespace" . }}
  labels: {{- include "mongodb.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
  {{- with (merge (.Values.primary.service.annotations | default dict) (.Values.commonAnnotations | default dict)) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.primary.service.type }}
  {{- if and (eq .Values.primary.service.type "ClusterIP") .Values.primary.service.clusterIP }}
  clusterIP: {{ .Values.primary.service.clusterIP }}
  {{- end }}
  ports:
    - name: tcp-mongodb
      port: {{ include "mongodb.servicePort" . }}
      targetPort: tcp-mongodb
      {{- if and (eq .Values.primary.service.type "NodePort") .Values.primary.service.nodePorts.mongodb }}
      nodePort: {{ .Values.primary.service.nodePorts.mongodb }}
      {{- end }}
  selector: {{- include "mongodb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: primary
