apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}
  namespace: {{ include "etcd.namespace" . }}
  labels: {{- include "etcd.labels" . | nindent 4 }}
  {{- with (merge (.Values.service.annotations | default dict) (.Values.commonAnnotations | default dict)) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: client
      port: {{ .Values.service.ports.client }}
      targetPort: client
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.client }}
      nodePort: {{ .Values.service.nodePorts.client }}
      {{- end }}
    - name: peer
      port: {{ .Values.service.ports.peer }}
      targetPort: peer
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.peer }}
      nodePort: {{ .Values.service.nodePorts.peer }}
      {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.containerPorts.metrics }}
      targetPort: metrics
    {{- end }}
  selector: {{- include "etcd.selectorLabels" . | nindent 4 }}
