{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ include "mongodb.namespace" . }}
  labels: {{- include "mongodb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "mongodb.rootPasswordKey" . }}: {{ include "mongodb.rootPassword" . | b64enc | quote }}
  {{- if (include "mongodb.username" .) }}
  {{ include "mongodb.userPasswordKey" . }}: {{ include "mongodb.userPassword" . | b64enc | quote }}
  {{- end }}
{{- end }}
