apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}-headless
  namespace: {{ include "zookeeper.namespace" . }}
  labels: {{- include "zookeeper.labels" . | nindent 4 }}
  {{- with .Values.service.headless.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: client
      port: {{ .Values.service.ports.client }}
      targetPort: client
    - name: follower
      port: {{ .Values.service.ports.follower }}
      targetPort: follower
    - name: election
      port: {{ .Values.service.ports.election }}
      targetPort: election
  selector: {{- include "zookeeper.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
