apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  namespace: {{ include "zookeeper.namespace" . }}
  labels: {{- include "zookeeper.labels" . | nindent 4 }}
  {{- with (merge (.Values.service.annotations | default dict) (.Values.commonAnnotations | default dict)) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: client
      port: {{ .Values.service.ports.client }}
      targetPort: client
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.client }}
      nodePort: {{ .Values.service.nodePorts.client }}
      {{- end }}
    - name: follower
      port: {{ .Values.service.ports.follower }}
      targetPort: follower
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.follower }}
      nodePort: {{ .Values.service.nodePorts.follower }}
      {{- end }}
    - name: election
      port: {{ .Values.service.ports.election }}
      targetPort: election
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.election }}
      nodePort: {{ .Values.service.nodePorts.election }}
      {{- end }}
  selector: {{- include "zookeeper.selectorLabels" . | nindent 4 }}
