apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-hl
  namespace: {{ include "mysql.namespace" . }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
  {{- with .Values.primary.service.headless.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-mysql
      port: {{ include "mysql.servicePort" . }}
      targetPort: tcp-mysql
  selector: {{- include "mysql.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: primary
