{{- if and (not .Values.cluster.enabled) (or .Values.sentinel.enabled (eq .Values.architecture "replication")) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis.fullname" . }}-replica
  namespace: {{ include "redis.namespace" . }}
  labels: {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: replica
spec:
  replicas: {{ .Values.replica.replicaCount }}
  selector:
    matchLabels: {{- include "redis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: replica
  serviceName: {{ include "redis.fullname" . }}-replica-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels: {{- include "redis.labels" . | nindent 8 }}
        app.kubernetes.io/component: replica
        {{- with .Values.replica.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.replica.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "redis.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      {{- with (concat .Values.global.imagePullSecrets .Values.image.pullSecrets) }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.replica.podSecurityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.replica.podSecurityContext.fsGroup }}
      {{- end }}
      {{- with .Values.replica.initContainers }}
      initContainers: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ include "redis.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.replica.containerSecurityContext.enabled }}
          securityContext:
            runAsUser: {{ .Values.replica.containerSecurityContext.runAsUser }}
            runAsGroup: {{ .Values.replica.containerSecurityContext.runAsGroup }}
            runAsNonRoot: {{ .Values.replica.containerSecurityContext.runAsNonRoot }}
            allowPrivilegeEscalation: {{ .Values.replica.containerSecurityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.replica.containerSecurityContext.readOnlyRootFilesystem }}
            capabilities:
              drop: {{- toYaml .Values.replica.containerSecurityContext.capabilities.drop | nindent 16 }}
            seccompProfile:
              type: {{ .Values.replica.containerSecurityContext.seccompProfile.type }}
          {{- end }}
          env:
            - name: REDIS_PORT
              value: {{ .Values.replica.containerPorts.redis | quote }}
            - name: REDIS_REPLICATION_MODE
              value: "replica"
            - name: REDIS_MASTER_HOST
              value: {{ include "redis.fullname" . }}{{- if .Values.sentinel.enabled }}-primary{{- end }}
            - name: REDIS_MASTER_PORT
              value: {{ .Values.primary.containerPorts.redis | quote }}
            {{- if .Values.auth.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis.secretName" . }}
                  key: {{ include "redis.secretPasswordKey" . }}
            - name: REDIS_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis.secretName" . }}
                  key: {{ include "redis.secretPasswordKey" . }}
            {{- end }}
            {{- with .Values.replica.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: tcp-redis
              containerPort: {{ .Values.replica.containerPorts.redis }}
          {{- if .Values.replica.startupProbe.enabled }}
          startupProbe:
            tcpSocket:
              port: tcp-redis
            initialDelaySeconds: {{ .Values.replica.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.replica.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.replica.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.replica.startupProbe.failureThreshold }}
            successThreshold: {{ .Values.replica.startupProbe.successThreshold }}
          {{- end }}
          {{- if .Values.replica.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: tcp-redis
            initialDelaySeconds: {{ .Values.replica.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.replica.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.replica.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.replica.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.replica.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.replica.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: tcp-redis
            initialDelaySeconds: {{ .Values.replica.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.replica.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.replica.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.replica.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.replica.readinessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.replica.resources }}
          resources: {{- toYaml .Values.replica.resources | nindent 12 }}
          {{- else if .Values.replica.resourcesPreset }}
          resources: {{- include "redis.resources" (dict "preset" .Values.replica.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: redis-data
              mountPath: {{ .Values.replica.persistence.mountPath }}
            {{- with .Values.replica.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.replica.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        {{- if not .Values.replica.persistence.enabled }}
        - name: redis-data
          emptyDir: {}
        {{- end }}
        {{- with .Values.replica.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.replica.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.replica.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.replica.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.replica.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels: {{- include "redis.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: replica
        {{- with .Values.replica.persistence.annotations }}
        annotations: {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes: {{- toYaml .Values.replica.persistence.accessModes | nindent 10 }}
        {{- $sc := .Values.global.defaultStorageClass | default .Values.global.storageClass | default .Values.replica.persistence.storageClass }}
        {{- if $sc }}
        storageClassName: {{ $sc }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.replica.persistence.size }}
  {{- end }}
{{- end }}
