{{- if and (not .Values.cluster.enabled) (or .Values.sentinel.enabled (eq .Values.architecture "replication")) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-replica-headless
  namespace: {{ include "redis.namespace" . }}
  labels: {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: replica
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-redis
      port: {{ .Values.replica.service.ports.redis }}
      targetPort: tcp-redis
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.containerPorts.metrics }}
      targetPort: metrics
    {{- end }}
  selector: {{- include "redis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: replica
{{- end }}
