apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-headless
  namespace: {{ include "kafka.namespace" . }}
  labels: {{- include "kafka.labels" . | nindent 4 }}
  {{- with .Values.service.headless.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: client
      port: {{ .Values.service.ports.client }}
      targetPort: client
    - name: controller
      port: {{ .Values.service.ports.controller }}
      targetPort: controller
  selector: {{- include "kafka.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
