apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ include "kafka.namespace" . }}
  labels: {{- include "kafka.labels" . | nindent 4 }}
  {{- with (merge (.Values.service.annotations | default dict) (.Values.commonAnnotations | default dict)) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: client
      port: {{ .Values.service.ports.client }}
      targetPort: client
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.client }}
      nodePort: {{ .Values.service.nodePorts.client }}
      {{- end }}
    - name: controller
      port: {{ .Values.service.ports.controller }}
      targetPort: controller
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.controller }}
      nodePort: {{ .Values.service.nodePorts.controller }}
      {{- end }}
  selector: {{- include "kafka.selectorLabels" . | nindent 4 }}
