{{- if .Values.schedule }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kubectl.fullname" . }}
  namespace: {{ include "kubectl.namespace" . }}
  labels: {{- include "kubectl.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      {{- if .Values.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      {{- end }}
      template:
        metadata:
          labels: {{- include "kubectl.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.podAnnotations }}
          annotations: {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "kubectl.serviceAccountName" . }}
          automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
          restartPolicy: {{ .Values.restartPolicy }}
          {{- with (concat .Values.global.imagePullSecrets .Values.image.pullSecrets) }}
          imagePullSecrets: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.podSecurityContext.enabled }}
          securityContext:
            fsGroup: {{ .Values.podSecurityContext.fsGroup }}
          {{- end }}
          containers:
            - name: kubectl
              image: {{ include "kubectl.image" . }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- if .Values.containerSecurityContext.enabled }}
              securityContext:
                runAsUser: {{ .Values.containerSecurityContext.runAsUser }}
                runAsGroup: {{ .Values.containerSecurityContext.runAsGroup }}
                runAsNonRoot: {{ .Values.containerSecurityContext.runAsNonRoot }}
                allowPrivilegeEscalation: {{ .Values.containerSecurityContext.allowPrivilegeEscalation }}
                readOnlyRootFilesystem: {{ .Values.containerSecurityContext.readOnlyRootFilesystem }}
                capabilities:
                  drop: {{- toYaml .Values.containerSecurityContext.capabilities.drop | nindent 20 }}
                seccompProfile:
                  type: {{ .Values.containerSecurityContext.seccompProfile.type }}
              {{- end }}
              {{- with .Values.command }}
              command: {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.args }}
              args: {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.extraEnvVars }}
              env: {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- if .Values.resources }}
              resources: {{- toYaml .Values.resources | nindent 16 }}
              {{- else if .Values.resourcesPreset }}
              resources: {{- include "kubectl.resources" (dict "preset" .Values.resourcesPreset) | nindent 16 }}
              {{- end }}
              {{- with .Values.extraVolumeMounts }}
              volumeMounts: {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .Values.extraVolumes }}
          volumes: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations: {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
