{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubectl.fullname" . }}
  namespace: {{ include "kubectl.namespace" . }}
  labels: {{- include "kubectl.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "kubectl.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- if .Values.networkPolicy.allowExternal }}
        - podSelector: {}
        {{- else }}
        - podSelector:
            matchLabels: {{- include "kubectl.selectorLabels" . | nindent 14 }}
        {{- end }}
      ports:
        {{- range .Values.networkPolicy.additionalRules }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  egress:
    - {}
{{- end }}
