{{- if and .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.clusterWide }}
kind: ClusterRole
metadata:
  name: {{ include "kubectl.fullname" . }}
  labels: {{- include "kubectl.labels" . | nindent 4 }}
{{- else }}
kind: Role
metadata:
  name: {{ include "kubectl.fullname" . }}
  namespace: {{ include "kubectl.namespace" . }}
  labels: {{- include "kubectl.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.rbac.rules }}
rules: {{- toYaml .Values.rbac.rules | nindent 2 }}
{{- else }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.clusterWide }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubectl.fullname" . }}
  labels: {{- include "kubectl.labels" . | nindent 4 }}
{{- else }}
kind: RoleBinding
metadata:
  name: {{ include "kubectl.fullname" . }}
  namespace: {{ include "kubectl.namespace" . }}
  labels: {{- include "kubectl.labels" . | nindent 4 }}
{{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubectl.serviceAccountName" . }}
    namespace: {{ include "kubectl.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.rbac.clusterWide }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ include "kubectl.fullname" . }}
{{- end }}
