{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ include "keycloak.namespace" . }}
  labels: {{- include "keycloak.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.parentRefs.name }}
      namespace: {{ .Values.httpRoute.parentRefs.namespace }}
  {{- if .Values.httpRoute.hostnames }}
  hostnames:
    {{- range .Values.httpRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: {{ .Values.httpRoute.pathType | default "PathPrefix" }}
            value: {{ .Values.httpRoute.path | default "/" }}
      backendRefs:
        - name: {{ include "keycloak.fullname" . }}
          port: {{ .Values.httpRoute.port | default 8080 }}
{{- end }}
