{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ include "keycloak.namespace" . }}
  labels: {{- include "keycloak.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  keycloak-admin-user: {{ .Values.auth.adminUser | b64enc | quote }}
  keycloak-admin-password: {{ include "keycloak.adminPassword" . | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.database.existingSecret) .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db" (include "keycloak.fullname" .) }}
  namespace: {{ include "keycloak.namespace" . }}
  labels: {{- include "keycloak.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.database.username }}
  db-username: {{ .Values.database.username | b64enc | quote }}
  {{- end }}
  db-password: {{ .Values.database.password | b64enc | quote }}
{{- end }}
