apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ include "keycloak.namespace" . }}
  labels: {{- include "keycloak.labels" . | nindent 4 }}
  {{- with (merge (.Values.service.annotations | default dict) (.Values.commonAnnotations | default dict)) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.http }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
    - name: management
      port: {{ .Values.containerPorts.management }}
      targetPort: management
  selector: {{- include "keycloak.selectorLabels" . | nindent 4 }}
