apiVersion: v2
name: mariadb
description: MariaDB relational database
type: application
version: "0.1.0"
appVersion: "12.1.2"
home: https://github.com/kubelauncher/charts
sources:
  - https://github.com/kubelauncher/docker
  - https://github.com/kubelauncher/charts
maintainers:
  - name: kubelauncher
    email: platform@kubelauncher.com
    url: https://www.kubelauncher.com
keywords:
  - mariadb
  - database
  - sql
  - mysql
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: "cosign"
  artifacthub.io/changes: |
    - kind: added
      description: Initial release of mariadb chart (appVersion 12.1.2)
