apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memcached.fullname" . }}
  namespace: {{ include "memcached.namespace" . }}
  labels: {{- include "memcached.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "memcached.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "memcached.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "memcached.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      {{- with (concat .Values.global.imagePullSecrets .Values.image.pullSecrets) }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: memcached
          image: {{ include "memcached.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext:
            runAsUser: {{ .Values.containerSecurityContext.runAsUser }}
            runAsGroup: {{ .Values.containerSecurityContext.runAsGroup }}
            runAsNonRoot: {{ .Values.containerSecurityContext.runAsNonRoot }}
            allowPrivilegeEscalation: {{ .Values.containerSecurityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.containerSecurityContext.readOnlyRootFilesystem }}
            capabilities:
              drop: {{- toYaml .Values.containerSecurityContext.capabilities.drop | nindent 16 }}
            seccompProfile:
              type: {{ .Values.containerSecurityContext.seccompProfile.type }}
          {{- end }}
          env:
            - name: MEMCACHED_MAX_MEMORY
              value: {{ .Values.memcachedMaxMemory | quote }}
            - name: MEMCACHED_THREADS
              value: {{ .Values.memcachedThreads | quote }}
            - name: MEMCACHED_MAX_CONNECTIONS
              value: {{ .Values.memcachedMaxConnections | quote }}
            - name: MEMCACHED_EXTRA_FLAGS
              value: {{ .Values.memcachedExtraFlags | quote }}
            {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: memcached
              containerPort: {{ .Values.containerPorts.memcached }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            tcpSocket:
              port: memcached
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: memcached
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: memcached
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- else if .Values.resourcesPreset }}
          resources: {{- include "memcached.resources" (dict "preset" .Values.resourcesPreset) | nindent 12 }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: memcached-exporter
          image: {{ .Values.metrics.image.registry }}/{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          args:
            - "--memcached.address=localhost:{{ .Values.containerPorts.memcached }}"
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.containerPorts.metrics }}
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
        {{- end }}
      {{- with .Values.extraVolumes }}
      volumes: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
