apiVersion: v1
kind: Service
metadata:
  name: {{ include "memcached.fullname" . }}
  namespace: {{ include "memcached.namespace" . }}
  labels: {{- include "memcached.labels" . | nindent 4 }}
  {{- with (merge (.Values.service.annotations | default dict) (.Values.commonAnnotations | default dict)) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: memcached
      port: {{ .Values.service.ports.memcached }}
      targetPort: memcached
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.memcached }}
      nodePort: {{ .Values.service.nodePorts.memcached }}
      {{- end }}
  selector: {{- include "memcached.selectorLabels" . | nindent 4 }}
