apiVersion: v2
name: memcached
description: Memcached in-memory caching system
type: application
version: "0.1.0"
appVersion: "1.6.40"
home: https://github.com/kubelauncher/charts
sources:
  - https://github.com/kubelauncher/docker
  - https://github.com/kubelauncher/charts
maintainers:
  - name: kubelauncher
    email: platform@kubelauncher.com
    url: https://www.kubelauncher.com
keywords:
  - memcached
  - cache
  - memory
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: "cosign"
  artifacthub.io/changes: |
    - kind: added
      description: Initial release of memcached chart (appVersion 1.6.40)
