{{- if .Values.commonConfiguration }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-configuration
  namespace: {{ include "redis.namespace" . }}
  labels: {{- include "redis.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  redis.conf: |
    bind 0.0.0.0
    port {{ .Values.primary.containerPorts.redis }}
    dir /data
    protected-mode no
    {{- if .Values.auth.enabled }}
    requirepass {{ include "redis.password" . }}
    {{- end }}
    {{- .Values.commonConfiguration | nindent 4 }}
{{- end }}
