{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ include "redis.namespace" . }}
  labels: {{- include "redis.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  redis-password: {{ include "redis.password" . | b64enc | quote }}
{{- end }}
