apiVersion: v2
name: keycloak
description: Keycloak identity and access management
type: application
version: "0.1.9"
appVersion: "26.5.3"
icon: https://cdn.simpleicons.org/keycloak
home: https://github.com/kubelauncher/charts
sources:
  - https://github.com/kubelauncher/docker
  - https://github.com/kubelauncher/charts
maintainers:
  - name: kubelauncher
    email: platform@kubelauncher.com
    url: https://www.kubelauncher.com
keywords:
  - keycloak
  - identity
  - authentication
  - oauth
  - oidc
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: EE19FA216B8349AC017C5279B4C062080CDC2061C264EE92CF98300E39FD40A8
    url: https://kubelauncher.github.io/charts/cosign.pub
  artifacthub.io/changes: |
    - kind: added
      description: Add Prometheus metrics via Quarkus health endpoint and ServiceMonitor
