{{- if not .Values.cluster.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis.fullname" . }}{{- if .Values.sentinel.enabled }}-primary{{- end }}
  namespace: {{ include "redis.namespace" . }}
  labels: {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
spec:
  replicas: {{ .Values.primary.count }}
  selector:
    matchLabels: {{- include "redis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: primary
  serviceName: {{ include "redis.fullname" . }}-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels: {{- include "redis.labels" . | nindent 8 }}
        app.kubernetes.io/component: primary
        {{- with .Values.primary.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.primary.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "redis.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      {{- with (concat .Values.global.imagePullSecrets .Values.image.pullSecrets) }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.primary.podSecurityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.primary.podSecurityContext.fsGroup }}
      {{- end }}
      {{- with .Values.primary.initContainers }}
      initContainers: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ include "redis.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.primary.containerSecurityContext.enabled }}
          securityContext:
            runAsUser: {{ .Values.primary.containerSecurityContext.runAsUser }}
            runAsGroup: {{ .Values.primary.containerSecurityContext.runAsGroup }}
            runAsNonRoot: {{ .Values.primary.containerSecurityContext.runAsNonRoot }}
            allowPrivilegeEscalation: {{ .Values.primary.containerSecurityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.primary.containerSecurityContext.readOnlyRootFilesystem }}
            capabilities:
              drop: {{- toYaml .Values.primary.containerSecurityContext.capabilities.drop | nindent 16 }}
            seccompProfile:
              type: {{ .Values.primary.containerSecurityContext.seccompProfile.type }}
          {{- end }}
          env:
            - name: REDIS_PORT
              value: {{ .Values.primary.containerPorts.redis | quote }}
            {{- if .Values.auth.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis.secretName" . }}
                  key: {{ include "redis.secretPasswordKey" . }}
            {{- end }}
            {{- with .Values.primary.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: tcp-redis
              containerPort: {{ .Values.primary.containerPorts.redis }}
          {{- if .Values.primary.startupProbe.enabled }}
          startupProbe:
            tcpSocket:
              port: tcp-redis
            initialDelaySeconds: {{ .Values.primary.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.primary.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.primary.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.primary.startupProbe.failureThreshold }}
            successThreshold: {{ .Values.primary.startupProbe.successThreshold }}
          {{- end }}
          {{- if .Values.primary.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: tcp-redis
            initialDelaySeconds: {{ .Values.primary.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.primary.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.primary.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.primary.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.primary.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.primary.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: tcp-redis
            initialDelaySeconds: {{ .Values.primary.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.primary.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.primary.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.primary.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.primary.readinessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.primary.resources }}
          resources: {{- toYaml .Values.primary.resources | nindent 12 }}
          {{- else if .Values.primary.resourcesPreset }}
          resources: {{- include "redis.resources" (dict "preset" .Values.primary.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: redis-data
              mountPath: {{ .Values.primary.persistence.mountPath }}
            {{- if .Values.commonConfiguration }}
            - name: redis-config
              mountPath: /opt/redis/etc/
              readOnly: true
            {{- end }}
            {{- with .Values.primary.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.primary.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        {{- if not .Values.primary.persistence.enabled }}
        - name: redis-data
          emptyDir: {}
        {{- end }}
        {{- if .Values.commonConfiguration }}
        - name: redis-config
          configMap:
            name: {{ include "redis.fullname" . }}-configuration
        {{- end }}
        {{- with .Values.primary.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.primary.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.primary.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.primary.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.primary.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels: {{- include "redis.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: primary
        {{- with .Values.primary.persistence.annotations }}
        annotations: {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes: {{- toYaml .Values.primary.persistence.accessModes | nindent 10 }}
        {{- $sc := .Values.global.defaultStorageClass | default .Values.global.storageClass | default .Values.primary.persistence.storageClass }}
        {{- if $sc }}
        storageClassName: {{ $sc }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.primary.persistence.size }}
  {{- end }}
{{- end }}
