apiVersion: v2
name: kafka
description: Apache Kafka distributed streaming platform
type: application
version: "0.1.0"
appVersion: "3.9.0"
icon: https://cdn.simpleicons.org/apachekafka
home: https://github.com/kubelauncher/charts
sources:
  - https://github.com/kubelauncher/docker
  - https://github.com/kubelauncher/charts
maintainers:
  - name: kubelauncher
    email: platform@kubelauncher.com
    url: https://www.kubelauncher.com
keywords:
  - kafka
  - streaming
  - messaging
  - event
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - kind: added
      description: Apache Kafka 3.9.0
      links:
        - name: Release Notes
          url: https://github.com/apache/kafka/releases/tag/3.9.0
