{{- if and (eq .Values.architecture "replicaset") (not .Values.replicaset.existingKeyfileSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.keyfileSecretName" . }}
  namespace: {{ include "mongodb.namespace" . }}
  labels: {{- include "mongodb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  keyfile: {{ randAlphaNum 756 | b64enc | quote }}
{{- end }}
