apiVersion: v2
name: openldap
description: OpenLDAP directory service
type: application
version: "0.1.1"
appVersion: "2.6.12"
icon: https://raw.githubusercontent.com/kubelauncher/charts/main/icons/openldap.svg
home: https://github.com/kubelauncher/charts
sources:
  - https://github.com/kubelauncher/docker
  - https://github.com/kubelauncher/charts
maintainers:
  - name: kubelauncher
    email: platform@kubelauncher.com
    url: https://www.kubelauncher.com
keywords:
  - openldap
  - ldap
  - directory
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: "cosign"
  artifacthub.io/changes: |
    - kind: added
      description: Initial release of openldap chart (appVersion 2.6.12)
