apiVersion: v2
name: openldap
description: OpenLDAP directory service
type: application
version: "0.1.0"
appVersion: "2.6.9"
home: https://github.com/kubelauncher/charts
sources:
  - https://github.com/kubelauncher/docker
  - https://github.com/kubelauncher/charts
maintainers:
  - name: kubelauncher
    email: platform@kubelauncher.com
    url: https://www.kubelauncher.com
keywords:
  - openldap
  - ldap
  - directory
