{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ include "postgresql.namespace" . }}
  labels: {{- include "postgresql.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "postgresql.adminPasswordKey" . }}: {{ include "postgresql.adminPassword" . | b64enc | quote }}
  {{- if and (include "postgresql.username" .) (ne (include "postgresql.username" .) "postgres") }}
  {{ include "postgresql.userPasswordKey" . }}: {{ include "postgresql.userPassword" . | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.replicationPassword }}
  {{ .Values.auth.secretKeys.replicationPasswordKey }}: {{ .Values.auth.replicationPassword | b64enc | quote }}
  {{- end }}
{{- end }}
