{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ include "mariadb.namespace" . }}
  labels: {{- include "mariadb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "mariadb.rootPasswordKey" . }}: {{ include "mariadb.rootPassword" . | b64enc | quote }}
  {{- if (include "mariadb.username" .) }}
  {{ include "mariadb.userPasswordKey" . }}: {{ include "mariadb.userPassword" . | b64enc | quote }}
  {{- end }}
{{- end }}
