{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-cluster
  namespace: {{ include "redis.namespace" . }}
  labels: {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster
  {{- with (merge (.Values.cluster.service.annotations | default dict) (.Values.commonAnnotations | default dict)) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.cluster.service.type }}
  {{- if and (eq .Values.cluster.service.type "ClusterIP") .Values.cluster.service.clusterIP }}
  clusterIP: {{ .Values.cluster.service.clusterIP }}
  {{- end }}
  ports:
    - name: tcp-redis
      port: {{ .Values.cluster.service.ports.redis }}
      targetPort: tcp-redis
      {{- if and (eq .Values.cluster.service.type "NodePort") .Values.cluster.service.nodePorts.redis }}
      nodePort: {{ .Values.cluster.service.nodePorts.redis }}
      {{- end }}
    - name: tcp-bus
      port: {{ .Values.cluster.service.ports.bus }}
      targetPort: tcp-bus
      {{- if and (eq .Values.cluster.service.type "NodePort") .Values.cluster.service.nodePorts.bus }}
      nodePort: {{ .Values.cluster.service.nodePorts.bus }}
      {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.containerPorts.metrics }}
      targetPort: metrics
    {{- end }}
  selector: {{- include "redis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cluster
{{- end }}
