apiVersion: v2
name: postgresql
description: PostgreSQL relational database
type: application
version: 0.1.0
appVersion: "18"
home: https://github.com/kubelauncher/charts
sources:
  - https://github.com/kubelauncher/docker
  - https://github.com/kubelauncher/charts
maintainers:
  - name: kubelauncher
    email: platform@kubelauncher.com
    url: https://www.kubelauncher.com
keywords:
  - postgresql
  - postgres
  - database
  - sql
  - replication
