{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openldap.fullname" . }}
  namespace: {{ include "openldap.namespace" . }}
  labels: {{- include "openldap.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "openldap.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- if .Values.networkPolicy.allowExternal }}
        - podSelector: {}
        {{- else }}
        - podSelector:
            matchLabels: {{- include "openldap.selectorLabels" . | nindent 14 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.containerPorts.ldap }}
        - protocol: TCP
          port: {{ .Values.containerPorts.ldaps }}
        {{- range .Values.networkPolicy.additionalRules }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  egress:
    - {}
{{- end }}
