{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openldap.fullname" . }}
  namespace: {{ include "openldap.namespace" . }}
  labels: {{- include "openldap.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  ldap-admin-password: {{ include "openldap.adminPassword" . | b64enc | quote }}
{{- end }}
