apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}-headless
  namespace: {{ include "openldap.namespace" . }}
  labels: {{- include "openldap.labels" . | nindent 4 }}
  {{- with .Values.service.headless.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: ldap
      port: {{ .Values.service.ports.ldap }}
      targetPort: ldap
    - name: ldaps
      port: {{ .Values.service.ports.ldaps }}
      targetPort: ldaps
  selector: {{- include "openldap.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
