apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}
  namespace: {{ include "openldap.namespace" . }}
  labels: {{- include "openldap.labels" . | nindent 4 }}
  {{- with (merge (.Values.service.annotations | default dict) (.Values.commonAnnotations | default dict)) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: ldap
      port: {{ .Values.service.ports.ldap }}
      targetPort: ldap
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.ldap }}
      nodePort: {{ .Values.service.nodePorts.ldap }}
      {{- end }}
    - name: ldaps
      port: {{ .Values.service.ports.ldaps }}
      targetPort: ldaps
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.ldaps }}
      nodePort: {{ .Values.service.nodePorts.ldaps }}
      {{- end }}
  selector: {{- include "openldap.selectorLabels" . | nindent 4 }}
