apiVersion: v1
kind: Service
metadata:
  name: {{ include "cassandra.fullname" . }}
  namespace: {{ include "cassandra.namespace" . }}
  labels: {{- include "cassandra.labels" . | nindent 4 }}
  {{- with (merge (.Values.service.annotations | default dict) (.Values.commonAnnotations | default dict)) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: cql
      port: {{ .Values.service.ports.cql }}
      targetPort: cql
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.cql }}
      nodePort: {{ .Values.service.nodePorts.cql }}
      {{- end }}
    - name: intra-node
      port: {{ .Values.service.ports.intraNode }}
      targetPort: intra-node
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.intraNode }}
      nodePort: {{ .Values.service.nodePorts.intraNode }}
      {{- end }}
    - name: tls-intra-node
      port: {{ .Values.service.ports.tlsIntraNode }}
      targetPort: tls-intra-node
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.tlsIntraNode }}
      nodePort: {{ .Values.service.nodePorts.tlsIntraNode }}
      {{- end }}
  selector: {{- include "cassandra.selectorLabels" . | nindent 4 }}
