{{- if not .Values.auth.existingPasswordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ include "rabbitmq.namespace" . }}
  labels: {{- include "rabbitmq.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  rabbitmq-password: {{ .Values.auth.password | default (randAlphaNum 10) | b64enc | quote }}
  {{- if not .Values.auth.existingErlangSecret }}
  rabbitmq-erlang-cookie: {{ .Values.auth.erlangCookie | default (randAlphaNum 32) | b64enc | quote }}
  {{- end }}
{{- end }}
