apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-headless
  namespace: {{ include "rabbitmq.namespace" . }}
  labels: {{- include "rabbitmq.labels" . | nindent 4 }}
  {{- with .Values.service.headless.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: amqp
      port: {{ .Values.service.ports.amqp }}
      targetPort: amqp
    - name: dist
      port: {{ .Values.service.ports.dist }}
      targetPort: dist
    - name: http-stats
      port: {{ .Values.service.ports.manager }}
      targetPort: stats
    - name: epmd
      port: {{ .Values.service.ports.epmd }}
      targetPort: epmd
  selector: {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
