apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ include "rabbitmq.namespace" . }}
  labels: {{- include "rabbitmq.labels" . | nindent 4 }}
  {{- with (merge (.Values.service.annotations | default dict) (.Values.commonAnnotations | default dict)) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: amqp
      port: {{ .Values.service.ports.amqp }}
      targetPort: amqp
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.amqp }}
      nodePort: {{ .Values.service.nodePorts.amqp }}
      {{- end }}
    - name: dist
      port: {{ .Values.service.ports.dist }}
      targetPort: dist
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.dist }}
      nodePort: {{ .Values.service.nodePorts.dist }}
      {{- end }}
    - name: http-stats
      port: {{ .Values.service.ports.manager }}
      targetPort: stats
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.manager }}
      nodePort: {{ .Values.service.nodePorts.manager }}
      {{- end }}
    - name: epmd
      port: {{ .Values.service.ports.epmd }}
      targetPort: epmd
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.epmd }}
      nodePort: {{ .Values.service.nodePorts.epmd }}
      {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: 15692
      targetPort: metrics
    {{- end }}
  selector: {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
