apiVersion: v2
name: redis
description: Redis in-memory data store
type: application
version: "0.2.14"
appVersion: "8.6.0"
icon: https://cdn.simpleicons.org/redis
home: https://github.com/kubelauncher/charts
sources:
  - https://github.com/kubelauncher/docker
  - https://github.com/kubelauncher/charts
maintainers:
  - name: kubelauncher
    email: platform@kubelauncher.com
    url: https://www.kubelauncher.com
keywords:
  - redis
  - cache
  - database
  - keyvalue
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: EE19FA216B8349AC017C5279B4C062080CDC2061C264EE92CF98300E39FD40A8
    url: https://kubelauncher.github.io/charts/cosign.pub
  artifacthub.io/changes: |
    - kind: added
      description: Add Prometheus metrics with redis-exporter sidecar and ServiceMonitor
