apiVersion: v2
name: redis
description: Redis in-memory data store
type: application
version: "0.2.7"
appVersion: "8.6.0"
icon: https://cdn.simpleicons.org/redis
home: https://github.com/kubelauncher/charts
sources:
  - https://github.com/kubelauncher/docker
  - https://github.com/kubelauncher/charts
maintainers:
  - name: kubelauncher
    email: platform@kubelauncher.com
    url: https://www.kubelauncher.com
keywords:
  - redis
  - cache
  - database
  - keyvalue
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - kind: fixed
      description: Announce cluster nodes by hostname instead of IP for resilient restarts
