{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ include "mysql.namespace" . }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "mysql.rootPasswordKey" . }}: {{ include "mysql.rootPassword" . | b64enc | quote }}
  {{- if (include "mysql.username" .) }}
  {{ include "mysql.userPasswordKey" . }}: {{ include "mysql.userPassword" . | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.architecture "replication" }}
  mysql-replication-password: {{ .Values.replication.password | default (randAlphaNum 10) | b64enc | quote }}
  {{- end }}
{{- end }}
