{{- if eq .Values.architecture "replication" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}-secondary-hl
  namespace: {{ include "mariadb.namespace" . }}
  labels: {{- include "mariadb.labels" . | nindent 4 }}
    app.kubernetes.io/component: secondary
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-mariadb
      port: {{ .Values.secondary.service.ports.mariadb }}
      targetPort: tcp-mariadb
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.containerPorts.metrics }}
      targetPort: metrics
    {{- end }}
  selector: {{- include "mariadb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: secondary
{{- end }}
