apiVersion: v2
name: rabbitmq
description: RabbitMQ message broker
type: application
version: "0.1.7"
appVersion: "4.2.3"
icon: https://cdn.simpleicons.org/rabbitmq
home: https://github.com/kubelauncher/charts
sources:
  - https://github.com/kubelauncher/docker
  - https://github.com/kubelauncher/charts
maintainers:
  - name: kubelauncher
    email: platform@kubelauncher.com
    url: https://www.kubelauncher.com
keywords:
  - rabbitmq
  - message queue
  - AMQP
  - broker
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: EE19FA216B8349AC017C5279B4C062080CDC2061C264EE92CF98300E39FD40A8
    url: https://kubelauncher.github.io/charts/cosign.pub
  artifacthub.io/changes: |
    - kind: added
      description: Add GPG provenance signing for Helm repo
