apiVersion: v2
name: zookeeper
description: Apache ZooKeeper distributed coordination service
type: application
version: "0.1.0"
appVersion: "3.9.3"
home: https://github.com/kubelauncher/charts
sources:
  - https://github.com/kubelauncher/docker
  - https://github.com/kubelauncher/charts
maintainers:
  - name: kubelauncher
    email: platform@kubelauncher.com
    url: https://www.kubelauncher.com
keywords:
  - zookeeper
  - coordination
  - distributed
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: "cosign"
  artifacthub.io/changes: |
    - kind: added
      description: Initial release of zookeeper chart (appVersion 3.9.3)
